Apt_Repos:
  - Name: Docker
    URL: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" 
  - Name: Kubectl
    URL: "deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main"
  - Name: Terminator
    Repo: ppa:mattrose/terminator
    Codename: Focal
  - Name: Helm
    URL: "deb https://baltocdn.com/helm/stable/debian/ all main"
