# Ansible role to execute a script
---
- name: scripts section
  set_fact:
    section: "{{ hostvars['localhost'].profile_json['Scripts'] }}"

- name: scripts scetion
  debug:
    msg: "{{ item.Script }}"
  with_items: "{{ section }}"

- name: Copy a script from the host and execute it on the remote
  script: "{{ item.Script }}"
  become: "{{ item.Become }}"
  become_user: "{{ item.Become_User }}"
  become_method: "{{ item.Become_Method }}"
  with_items: "{{ section }}"

