# --- special colors ---

[Background]
Color=33,33,43

[BackgroundIntense]
Color=33,33,43

[Foreground]
Color=184,210,225

[ForegroundIntense]
Color=184,210,225
Bold=true

# --- standard colors ---

[Color0]
Color=33,33,43

[Color0Intense]
Color=55,59,65

[Color1]
Color=242,116,138

[Color1Intense]
Color=247,104,90

[Color2]
Color=135,206,106

[Color2Intense]
Color=160,240,141

[Color3]
Color=202,203,100

[Color3Intense]
Color=255,236,116

[Color4]
Color=57,165,211

[Color4Intense]
Color=78,169,255

[Color5]
Color=204,119,210

[Color5Intense]
Color=254,107,253

[Color6]
Color=94,199,187

[Color6Intense]
Color=96,212,201

[Color7]
Color=168,195,200

[Color7Intense]
Color=218,223,224

# --- general options ---

[General]
Description=terminal.sexy
Opacity=1
Wallpaper=
