internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  database: nextcloud
  user: nextcloud
  password: changeme
  host: 127.0.0.1:5432

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: changeme
        database: nextcloud

  primary:
    persistence:
      enabled: true

nextcloud:
  configs:
    s3.config.php: |-
      <?php
      $CONFIG = array (
        'objectstore' => array(
          'class' => '\\OC\\Files\\ObjectStore\\S3',
          'arguments' => array(
            'bucket'     => 'nextcloud',
            'autocreate' => true,
            'hostname'   => 's3.us-west-002.backblazeb2.com',
            'port'       => 443,
            'key'        => 'beepboop',
            'secret'     => 'secret meeps',
            'region'     => 'us-west-002',
            'use_ssl'    => true
          )
        )
      );
