# vestigial, not currently used
---
- name: gather data
  set_fact:
    key_data: "{{ hostvars['localhost'].profile_json['Apt_Pass_2'] }}"
    debug: "{{ hostvars['localhost'].debug }}"
    squash: "{{ hostvars['localhost'].squash }}"

- name: "Generate optimized name list"
  set_fact:
    package_list: "{{ package_list + [ item.Name ] }}"
  with_items:
  - "{{ hostvars['localhost'].profile_json['Apt_Pass_2'] }}"
  vars:
    package_list: []

- name: displaying apt packages to install from config file
  debug:
    msg: "{{ item }}"
  with_items: "{{ key_data }}"
  when:
    - debug | bool

- name: squash install
  apt:
    name: "{{ package_list }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  when:
     - squash | bool

- name: Manage package
  apt:
    name: "{{ item.Name }}"
    state: "{{ item.State | default('present') }}"
  with_items: "{{ key_data }}"
  become: yes
  become_user: root
  become_method: sudo
  when:
     - item.Version is undefined
     - not squash

- name: Manage versioned package
  apt:
    name: "{{ '='.join((item.Name, item.Version)) }}"
    state: "{{ item.State }}"
  with_items: "{{ key_data }}"
  become: yes
  become_user: root
  become_method: sudo
  when:
     - item.Version is defined
     - not squash

- name: mark packages to be held
  dpkg_selections:
    name: "{{ item.Name }}"
    selection: hold
  with_items: "{{ key_data }}"
  become: yes
  become_user: root
  become_method: sudo
  when:
    - item.Version is defined
    - item.Hold | bool
    - not squash

