# extra stuff Dockerfile to include all the other stuff you might need, for arm
FROM --platform=linux/arm64 jessbeot/onboardme:latest

# k9s - k8s dashboard tui
RUN curl -LO https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_arm64.tar.gz /tmp/

# for installing helm, a package manager for k8s
RUN curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null && \
    sudo apt-get install apt-transport-https --yes && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list && \
    sudo apt-get update && \
    sudo apt-get install helm

# if tfenv is needed: https://github.com/tfutils/tfenv#manual

# install gh - github's CLI
# https://github.com/cli/cli/blob/trunk/docs/install_linux.md
RUN type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y) && \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \ && \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \ && \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \ && \
    && sudo apt update \ && \
    && sudo apt install gh -y
