- name: Creates a "PATH=" on top of crontab
  cron:
    user: "{{ item.user }}"
    name: "{{ item.name }}"
    env: "{{ item.env }}"
    job: "{{ item.job }}"
  with_items: "{{ hostvars['localhost']['job_list']['cron_config']['Path'] }}"

- name: Creates a "SHELL=" on top of crontab
  cron:
    user: "{{ item.user }}"
    name: "{{ item.name }}"
    env: "{{ item.env }}"
    job: "{{ item.job }}"
  with_items: "{{ hostvars['localhost']['job_list']['cron_config']['Shell'] }}"

- name: Add cron jobs
  cron:
    user: "{{ item.user }}"
    name: "{{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
    state: "{{ item.state }}"
  with_items: "{{ hostvars['localhost']['job_list']['cron_config']['jobs'] }}"