Files:
  - Name: Copy the modified environment file
    Source: "/home/max/Desktop/repos/ark8de/resources/synced_directory/personalization/environment"
    Dest: "/etc/environment"
    State: "transfer"
  - Name: Copy the console setup
    Source: "/home/max/Desktop/repos/ark8de/resources/synced_directory/personalization/console-setup"
    Dest: "/etc/default/console-setup"
    State: "transfer"
  - Name: Copy the .zsh file
    Source: "/home/max/Desktop/repos/ark8de/resources/synced_directory/personalization/.zshrc"
    Dest: "/home/vmadmin/.zshrc"
    State: "transfer"
  - Name: Copy the grub config 
    Source: "/home/max/Desktop/repos/ark8de/resources/synced_directory/personalization/grub"
    Dest: "/etc/default/grub"
    State: "transfer"
  - Name: Copy the keyboard config 
    Source: "/home/max/Desktop/repos/ark8de/resources/synced_directory/personalization/keyboard"
    Dest: "/etc/default/keyboard"
    State: "transfer"
Commands:
  - Command: update-grub
    Become: yes
    Become_User: root
    Become_Method: sudo