---
# Update package list on ubuntu host
- name: package update
  set_fact:
    data: "{{ hostvars['localhost'].profile_json['Package_Update'] }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: "{{ item.Update }}"
  become: yes
  become_user: root
  become_method: sudo
  with_items: "{{ data }}"
  when:
    - item.Update is defined
    - item.Update | bool

- name: Clean unwanted olderstuff
  apt:
   autoremove: "{{ item.Autoremove }}"
   purge: yes
  become: yes
  become_user: root
  become_method: sudo
  with_items: "{{ data }}"
  when:
    - item.Autoremove is defined
    - item.Autoremove | bool
